# Generated by Django 4.1.7 on 2023-04-02 06:37

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state',
            field=django_fsm.FSMField(default='available', max_length=50),
        ),
    ]
